# Generated by Django 5.0.6 on 2025-12-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='card_image',
            field=models.ImageField(null=True, upload_to='player_cards/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo/'),
        ),
    ]
