# Generated by Django 4.2.1 on 2025-12-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sold_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
