# Generated by Django 5.1.4 on 2026-02-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_player_sold_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='manager_card',
            field=models.ImageField(blank=True, null=True, upload_to='manager_cards/'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
